config/routes.rb
Bandjob::Application.routes.draw do
  root :to => 'Jobs#index'
  resources :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  before_validation_on_create :set_expires_on

  validates_presence_of :subject, :description, :organization

  def self.index
    active.newest_first
  end

  protected

  def self.active
    where('jobs.expires_on > :now', :now => Time.now)
  end

  def self.newest_first
    order('jobs.created_at DESC')
  end

  def set_expires_on
    self.expires_on ||= 2.weeks.from_now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  respond_to :html, :atom, :only => :index

  def index
    @jobs = Job.index
  end

  def new
    @job = Job.new
    @job.expires_on = 2.weeks.from_now
  end

  def create
    @job = Job.new(params[:job])
    if @job.save
      flash[:notice] = 'Your job ad has been posted.'
      redirect_to jobs_path
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
    # TODO: QR code
  end
end

app/helpers/body_class_helper.rb
module BodyClassHelper
  # TODO: move this into a gem/plugin
  def body_class
    qualified_controller_name = controller.controller_path.gsub('/','-')
    "#{qualified_controller_name} #{qualified_controller_name}-#{controller.action_name}"
  end
end

app/helpers/job_helper.rb
module JobHelper
  def description_with_contacts(job, description)
    out = description
    if job.email.present?
      out << raw(<<-HTML)
      <p><a href="mailto:#{job.email}">#{job.email}</a></p>
      HTML
    end
    if job.phone.present?
      out << raw(<<-HTML)
      <p><a href="tel://#{job.phone}">#{job.phone}</a></p>
      HTML
    end
    out
  end
end

app/views/jobs/_job.html.erb
<li>
  <h4><%= job.created_at.to_s(:posted_on) %></h4>
  <h2><%= link_to job_path(job) do %><%= job.subject %><% end %></h2>
  <h3><%= job.organization %></h3>
</li>

app/views/jobs/index.html.erb
<% content_for :title, 'Android Job Listings near Boston' %>
<% content_for :head do %>
  <%= auto_discovery_link_tag :atom, jobs_url(:format => :atom), :title => 'Feed of Boston Android jobs' %>
<% end %>

<% content_for :header do %>
  <p><%= link_to 'Post a new job', new_job_path %></p>
<% end %>

<ul id="job-list" class="clearfix">
  <%= render :partial => 'job', :collection => @jobs %>
</ul>

app/views/jobs/new.html.erb
<% content_for :title, 'New ad' %>

<div id="new-job">
  <h2>Post a job listing</h2>

  <% semantic_form_for @job do |form| %>
    <% form.inputs do %>
      <%= form.input :subject %>
      <%= form.input :organization %>
      <%= form.input :description %>
      <%= form.input :expires_on, :start_year => Time.now.year %>
      <%= form.input :email %>
      <%= form.input :phone %>
    <% end %>
    <% form.buttons do %>
      <%= form.commit_button 'Post ad' %>
    <% end %>
  <% end %>
</div>

app/views/jobs/show.html.erb
<% content_for :title, @job.subject %>

<div id="job-post">
  <h2 class="job-title"><%= @job.subject %></h2>

  <p>Posted on <%= @job.created_at.to_s(:posted_on) %> by <%= @job.organization %>.</p>

  <div id="description">
    <%= auto_link simple_format(@job.description) %>
  </div>

  <ul id="contact-methods">
    <% if @job.email.present? %>
      <li><%= mail_to @job.email, 'Contact by email' %></li>
    <% end %>

    <% if @job.phone.present? %>
      <li><%= link_to 'Contact by phone', "tel://#{@job.phone}" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Job board for Android developers near Boston, MA.">
    <title><%= yield :title %> - Boston Android job board</title>
    <link rel="icon" href="favicon.ico">
    <%= stylesheet_link_tag 'application', :media => 'all', :cache => true %>
    <%= csrf_meta_tag %>
    <%= yield :head %>
  </head>
  <body class="<%= body_class %>">

    <div id="container">
      <h1>Android Job Listings near Boston</h1>
      <ul id="nav">
        <li><%= link_to 'Full job list', jobs_path %> <%= link_to image_tag('atom.png'), jobs_url(:format => :atom), :class => 'atom-icon' %></li>
        <li><%= link_to 'Post a new job', new_job_path %></li>
      </ul>

      <%= render :partial => 'shared/flashes' -%>

      <%= yield -%>

      <p id="footer">Brought to you by the <%= link_to 'Boston Android developers group', 'http://bostonandroid.org/' %>.</p>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end -%>
</div>